spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/caching_db
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: caching
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis

logging:
  level:
    org.springframework.cache: DEBUG

